"""Adiciona imagem_url ao item

Revision ID: 00ff67cac9b3
Revises: 556dd53bbbfc
Create Date: 2025-10-18 19:47:44.795439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ff67cac9b3'
down_revision = '556dd53bbbfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_url', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('imagem_url')

    # ### end Alembic commands ###
